# Generated by Django 4.2.1 on 2023-12-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nome")),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                ("message", models.CharField(max_length=2000, verbose_name="mensagem")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True, max_length=2000, verbose_name="resposta"
                    ),
                ),
                (
                    "response_date",
                    models.DateTimeField(blank=True, verbose_name="respondido em"),
                ),
            ],
            options={
                "verbose_name": "mensagem",
                "verbose_name_plural": "mensagens",
                "ordering": ["-created_at"],
            },
        ),
    ]
